Mvc/Areas/Identity/Controllers/SignupController.cs
using AutoMapper;
using Entities.Concrete;
using Entities.Dtos;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Mvc.Areas.Identity.Models;

namespace Mvc.Areas.Identity.Controllers
{
    [Area("Identity")]

    public class SignupController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly IMapper _mapper;
        public SignupController(UserManager<User> userManager, SignInManager<User> signInManager,
            IMapper mapper)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _mapper = mapper;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Signup(SignupDto signupDto)
        {
            if (ModelState.IsValid)
            {
                var user = _mapper.Map<User>(signupDto);
                user.SecurityStamp = Guid.NewGuid().ToString();
                user.Picture = "~/img/UserImages/defaultUser.jpg";
                //isim sayisim eklenecek
                var result = await _userManager.CreateAsync(user, signupDto.Password);
                List<string> roles = new List<string> { "Article.Create", "Article.Read", "AdminArea.Home.Read" };
                await _userManager.AddToRolesAsync(user, roles);
                if (user != null)
                {
                    if (result.Succeeded)
                    {
                        var token = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                        var confirmationLink = Url.Action("ConfirmEmail", "Email", new { token, email = user.Email }, Request.Scheme);
                        EmailHelper emailHelper = new EmailHelper();
                        bool emailResponse = emailHelper.SendEmail(user.Email, confirmationLink);
                        if (emailResponse)
                        {
                            await _signInManager.SignInAsync(user, isPersistent: false);
                            return RedirectToAction("index", "Home", new { area = "Admin" });
                        }
                        else
                        {
                            return View("Index");
                        }
                    }
                    else
                    {
                        foreach (var err in result.Errors)
                        {
                            ModelState.AddModelError("", err.Description);
                        }

                        return View("Index", signupDto);
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "hata");
                    return View("Index");
                }
            }
            return View("Index");
        }
    }
}

Mvc/Areas/Login/Controllers/SignupController.cs
using AutoMapper;
using Entities.Concrete;
using Entities.Dtos;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Mvc.Areas.Login.Controllers
{
    [Area("Login")]
    public class SignupController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly IMapper _mapper;
        public SignupController(UserManager<User> userManager, SignInManager<User> signInManager, IMapper mapper)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _mapper = mapper;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Signup(SignupDto signupDto)
        {
            if (ModelState.IsValid)
            {
                var user = _mapper.Map<User>(signupDto);
                user.UserPicture = "Default/defaultUser.jpg";
                var result = await _userManager.CreateAsync(user, signupDto.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("index", "Home", new { area = "Admin" });
                }
                foreach (var err in result.Errors)
                {
                    ModelState.AddModelError("", err.Description);
                }
                ModelState.AddModelError(string.Empty, "Gecersiz giris islemi");
            }
            return View("Index");
        }
    }
}

Mvc/Areas/Login/Views/Signup/Index.cshtml
@model Entities.Dtos.SignupDto
@{
    Layout = "_userLoginLayout";
    ViewBag.Title = "Kayit Ol";
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-7">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h3 class="text-center font-weight-light my-4">Hesap Olustur</h3></div>
                <div class="card-body">
                    <form asp-area="Login" asp-controller="Signup" asp-action="Signup" method="post">
                        <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                        <div asp-validation-summary="All" class="text-danger" id="validation-summary" aria-hidden="true" style="display: none;"></div>
                        <div class="form-row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="small mb-1" asp-for="UserName"></label>
                                    <input class="form-control py-4" asp-for="UserName" type="text" />
                                    <span class="text-danger" asp-validation-for="UserName"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="small mb-1" asp-for="Email"></label>
                            <input class="form-control py-4" asp-for="Email" type="email" aria-describedby="emailHelp" />
                            <span class="text-danger" asp-validation-for="Email"></span>
                        </div>
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="small mb-1" asp-for="Password"></label>
                                    <input class="form-control py-4" asp-for="Password" type="password" />
                                    <span class="text-danger" asp-validation-for="Password"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="small mb-1" asp-for="PasswordConfirm"></label>
                                    <input class="form-control py-4" asp-for="PasswordConfirm" type="password" />
                                    <span class="text-danger" asp-validation-for="PasswordConfirm"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group mt-4 mb-0">
                            <button type="submit" class="btn btn-primary btn-block"><span class="fas fa-save"></span> Kaydol</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <a class="btn btn-primary" asp-area="Login" asp-controller="Login" asp-action="Index">Oturum ac</a>
                </div>
            </div>
        </div>
    </div>
</div>