Mvc/ViewComponents/RightSideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mvc.Models;
using Services.Abstract;

namespace Mvc.ViewComponents
{
    public class RightSideBarViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;
        private readonly IArticleService _articleService;

        public RightSideBarViewComponent(ICategoryService categoryService, IArticleService articleService)
        {
            _categoryService = categoryService;
            _articleService = articleService;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categoriesResult = await _categoryService.GetAllByNonDeletedAndActiveAsync();
            var articlesResult = await _articleService.GetAllByViewCountAsync(false, 5);
            return View(new RightSideBarViewModel
            {
                Categories = categoriesResult.Data.Categories,
                Articles = articlesResult.Data.Articles
            });
        }
    }
}

Mvc/Views/Shared/_AboutLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="@ViewBag.Description" />
    <meta name="author" content="@ViewBag.Author" />
    <meta name="keywords" content="@ViewBag.Tags" />
    <title>Design - Ana Sayfa</title>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/BlogHome/css/styles.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" crossorigin="anonymous"/>
    <script src="https://kit.fontawesome.com/5d6e25e9b6.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/js/all.min.js" integrity="sha512-rpLlll167T5LJHwp0waJCh3ZRf7pO6IT1+LZOhAyP6phAirwchClbTZV3iqL3BMrVxIYRbzGTpli4rfxsCK6Vw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link href="~/BlogHome/css/site.css" />
</head>
<body>
    <!-- Responsive navbar-->
    <partial name="_MainMenuPartial" />
    <!-- Page content-->
    <div class="container mt-5">

        <div class="row">
            <!-- Blog Entries Column -->
            @RenderBody()

            <!-- Sidebar Widgets Column -->
            @*@await Component.InvokeAsync("RightSideBar")*@
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Tüm hakları saklıdır &copy; Design Blog 2023</p>
        </div>
        <!-- /.container -->
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/BlogHome/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

Mvc/Views/Shared/_ArticleLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="@ViewBag.Description" />
    <meta name="author" content="@ViewBag.Author" />
    <meta name="keywords" content="@ViewBag.Tags" />
    <title>Design - Ana Sayfa</title>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/BlogHome/css/styles.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" crossorigin="anonymous"/>
</head>
<body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Design Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" action="Index">
                            Ana Sayfa
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" action="About">Hakkında</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" action="Contact">İletişim</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page content-->
    <div class="container mt-5">

        <div class="row">
            <!-- Blog Entries Column -->
            @RenderBody()

            <!-- Sidebar Widgets Column -->
            @await Component.InvokeAsync("RightSideBar")
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Tüm hakları saklıdır &copy; Design Blog 2023</p>
        </div>
        <!-- /.container -->
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/BlogHome/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

Mvc/Views/Shared/_ContactLayout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="@ViewBag.Description" />
    <meta name="author" content="@ViewBag.Author" />
    <meta name="keywords" content="@ViewBag.Tags" />
    <title>@ViewBag.Title - Design</title>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/BlogHome/css/styles.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" crossorigin="anonymous"/>
    <script src="https://kit.fontawesome.com/5d6e25e9b6.js" crossorigin="anonymous"></script>
    <link href="~/BlogHome/css/contact-page.css" />
</head>
<body>
    <!-- Responsive navbar-->
    <partial name="_MainMenuPartial" />
    <!-- Page content-->
    <div class="container mt-5">

        <div class="row">
            <!-- Blog Entries Column -->
            @RenderBody()

            <!-- Sidebar Widgets Column -->
            @*@await Component.InvokeAsync("RightSideBar")*@
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
    <!-- Footer -->
    @*<footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Tüm hakları saklıdır &copy; Design Blog 2023</p>
        </div>
        <!-- /.container -->
    </footer>*@
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/BlogHome/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

Mvc/Views/Shared/_Layout.cshtml
@using Entities.Concrete;
@using Microsoft.Extensions.Options
@inject IOptions<WebSiteInfo> WebSiteInfo
@{
    var webSiteInfo = WebSiteInfo.Value;

}
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="@webSiteInfo.SeoDescription" />
    <meta name="keywords" content="@webSiteInfo.SeoTags"/>
    <meta name="author" content="@webSiteInfo.SeoAuthor" />
    @*Design | @webSiteInfo.Title 'da eklenebilir*@
    <title>Design - Ana Sayfa</title>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/BlogHome/css/styles.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/js/all.min.js" integrity="sha512-rpLlll167T5LJHwp0waJCh3ZRf7pO6IT1+LZOhAyP6phAirwchClbTZV3iqL3BMrVxIYRbzGTpli4rfxsCK6Vw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>
<body>
    <!-- Responsive navbar-->
    <partial name="_MainMenuPartial" />
    <!-- Page content-->
    <div class="container mt-5">

        <div class="row">
            <!-- Blog Entries Column -->
            @RenderBody()

            <!-- Sidebar Widgets Column -->
            @await Component.InvokeAsync("RightSideBar")
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Tüm hakları saklıdır &copy; Design Blog 2023</p>
        </div>
        <!-- /.container -->
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/BlogHome/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

Mvc/Views/Shared/_MainMenuPartial.cshtml
@using Microsoft.Extensions.Options
@using Entities.Concrete
@inject IOptionsSnapshot<WebSiteInfo> WebSiteInfo
@{
    var webSiteInfo = WebSiteInfo.Value;
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Design Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" action="Index">
                        Ana Sayfa
                        @*@webSiteInfo.MenuTitle'da eklenebilir*@
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="About">Hakkında</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Contact">İletişim</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="Identity" asp-controller="Login" asp-action="Login">Yönetim Paneli</a>
                </li>
            </ul>
        </div>
    </div>
</nav>