Mvc/Areas/Admin/Controllers/HomeController.cs
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mvc.Areas.Admin.Models;
using Services.Abstract;
using Shared.Utilities.Results.ComplexTypes;

namespace Mvc.Areas.Admin.Controllers
{

    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICategoryService _cateogryService;
        private readonly ICommentService _commentService;
        private readonly IArticleService _articleService;


        public HomeController(UserManager<User> userManager, ICategoryService cateogryService, ICommentService commentService, IArticleService articleService)
        {
            _userManager = userManager;
            _cateogryService = cateogryService;
            _commentService = commentService;
            _articleService = articleService;
        }

        [Authorize(Roles = "SuperAdmin,AdminArea.Home.Read")]
        public async Task<IActionResult> Index()
        {
            //tum iceriklerin sayisinin index saytfasina dinamik olarak getirilmesi
            var categoriesCount = await _cateogryService.CountByNonDeletedAsync();
            var articlesCount = await _articleService.CountByNonDeletedAsync();
            var commentCount = await _commentService.CountByNonDeletedAsync();
            var userCount = await _userManager.Users.CountAsync();
            var article = await _articleService.GetAllAsync();

            if (categoriesCount.ResultStatus == ResultStatus.Success && articlesCount.ResultStatus == ResultStatus.Success
                && commentCount.ResultStatus == ResultStatus.Success && userCount > -1 && article.ResultStatus == ResultStatus.Success)
            {
                return View(new DashboardViewModel
                {
                    CategoriesCount = categoriesCount.Data,
                    ArticlesCount = articlesCount.Data,
                    CommentsCount = commentCount.Data,
                    UsersCount = userCount,
                    Articles = article.Data
                });
            }
            return NotFound();
        }
    }
}

Mvc/Areas/Admin/Controllers/UserController.cs
using AutoMapper;
using Entities.ComplexTypes;
using Entities.Concrete;
using Entities.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mvc.Areas.Admin.Models;
using Mvc.Helpers.Abstract;
using NToastNotify;
using Shared.Utilities.Extensions;
using Shared.Utilities.Results.ComplexTypes;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]

    //kullanici bazli yetkilendirme
    public class UserController : BaseController
    {
        private readonly SignInManager<User> _signInManager;
        private readonly IToastNotification _toastNotification;

        public UserController(UserManager<User> userManager, IMapper mapper, SignInManager<User> signInManager, IImageHelper imageHelper, IToastNotification toastNotification) : base(userManager, mapper, imageHelper)
        {
            _signInManager = signInManager;
            _toastNotification = toastNotification;
        }

        //authorize area kismina eklenirse sonsuz dongu olusur
        //tek tek actionlara eklenmeli
        [Authorize(Roles = "SuperAdmin,User.Read")]
        public async Task<IActionResult> Index()
        {
            var users = await UserManager.Users.ToListAsync();
            return View(new UserListDto
            {
                Users = users,
                resultStatus = ResultStatus.Success
            });
        }

        [Authorize(Roles = "SuperAdmin,User.Read")]
        [HttpGet]
        public async Task<JsonResult> GetAllUsers()
        {
            var users = await UserManager.Users.ToListAsync();
            var userListDto = JsonSerializer.Serialize(new UserListDto
            {
                Users = users,
                resultStatus = ResultStatus.Success
            }, new JsonSerializerOptions
            {
                ReferenceHandler = ReferenceHandler.Preserve
            });
            return Json(userListDto);
        }


        [Authorize(Roles = "SuperAdmin, User.Create")]
        [HttpGet]
        public IActionResult Add()
        {
            return PartialView("_UserAddPartial");
        }


        [Authorize(Roles = "SuperAdmin,User.Create")]
        [HttpPost]
        public async Task<IActionResult> Add(UserAddDto userAddDto)
        {
            if (ModelState.IsValid)
            {
                var uploadedResult = await ImageHelper.Upload(userAddDto.UserName, userAddDto.PictureFile, PictureType.User);
                userAddDto.Picture = uploadedResult.ResultStatus == ResultStatus.Success
                    ? uploadedResult.Data.FullName
                    : "UserImages/defaultUser.jpg";
                //Imagehelper ile resim adi atama
                var user = Mapper.Map<User>(userAddDto);
                user.EmailConfirmed = true;
                var result = await UserManager.CreateAsync(user, userAddDto.Password);
                //kullanici ekleme
                if (result.Succeeded)//identityresult doner
                {
                    var userAddAjax = JsonSerializer.Serialize(new UserAddAjaxViewModel
                    {
                        UserDto = new UserDto
                        {
                            resultStatus = ResultStatus.Success,
                            Message = $"{user.UserName} adli kullanici eklenmistir",
                            User = user
                        },
                        UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", userAddDto)
                    });
                    return Json(userAddAjax);
                }
                else
                {
                    foreach (var err in result.Errors)
                    {
                        ModelState.AddModelError("", err.Description);
                    }
                    var userAddAjaxError = JsonSerializer.Serialize(new UserAddAjaxViewModel
                    {
                        UserAddDto = userAddDto,
                        UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", userAddDto)
                    });
                    return Json(userAddAjaxError);
                    //identity tarafindaki hatayi frtonende gosterme
                }
            }
            var userAddAjaxErrorState = JsonSerializer.Serialize(new UserAddAjaxViewModel
            {
                UserAddDto = userAddDto,
                UserAddPartial = await this.RenderViewToStringAsync("_UserAddPartial", userAddDto)
            });
            return Json(userAddAjaxErrorState);
        }


        [Authorize(Roles = "SuperAdmin,User.Delete")]
        [HttpPost]
        public async Task<IActionResult> Remove(int userId)
        {
            var user = await UserManager.FindByIdAsync(userId.ToString());
            var result = await UserManager.DeleteAsync(user);
            if (result.Succeeded)
            {
                var deletedUser = JsonSerializer.Serialize(new UserDto
                {
                    resultStatus = ResultStatus.Success,
                    Message = $"{user.UserName} adli kullanici silinmistir",
                    User = user
                });
                return Json(deletedUser);
            }
            else
            {
                string errMessages = string.Empty;
                foreach (var err in result.Errors)
                {
                    errMessages = $"*{err.Description}\n";
                }
                var deletedUserErrorModel = JsonSerializer.Serialize(new UserDto
                {
                    resultStatus = ResultStatus.Error,
                    Message = $"{user.UserName} silinirken bazi hatalar olustu\n{errMessages}",
                    User = user
                });
                return Json(deletedUserErrorModel);
            }
        }


        [Authorize(Roles = "SuperAdmin,User.Update")]
        [HttpGet]
        public async Task<PartialViewResult> Update(int userId)
        //partialviewresult da kullanilabilir (IActionResult yerine)
        {
            var user = await UserManager.Users.FirstOrDefaultAsync(u => u.Id == userId);
            //findbyidasync yerine firstordefaultasync de kullanilabilir
            var userUpdateDto = Mapper.Map<UserUpdateDto>(user);
            return PartialView("_UserUpdatePartial", userUpdateDto);
            //userupdatepartial viewi ve userupdatedto yu geri don
        }


        [Authorize(Roles = "SuperAdmin,User.Update")]
        [HttpPost]
        public async Task<IActionResult> Update(UserUpdateDto userUpdateDto)
        {
            if (ModelState.IsValid)
            {
                bool isPictureUploaded = false;
                var oldUser = await UserManager.FindByIdAsync(userUpdateDto.Id.ToString());
                var oldPicture = oldUser.Picture;
                if (userUpdateDto.PictureFile != null)
                {
                    var uploadedResult = await ImageHelper.Upload(userUpdateDto.UserName, userUpdateDto.PictureFile, PictureType.User);
                    userUpdateDto.Picture = uploadedResult.ResultStatus == ResultStatus.Success
                        ? uploadedResult.Data.FullName
                        : "UserImages/defaultUser.jpg";
                    if (oldPicture != "UserImages/defaultUser.jpg")
                    {
                        isPictureUploaded = true;
                    }
                }
                var updatedUser = Mapper.Map(userUpdateDto, oldUser);
                var result = await UserManager.UpdateAsync(updatedUser);
                if (result.Succeeded)
                {
                    if (isPictureUploaded)
                    {
                        ImageHelper.Delete(oldPicture);
                    }
                    var userUpdateAjax = JsonSerializer.Serialize(new UserUpdateAjaxViewModel
                    {
                        UserDto = new UserDto
                        {
                            resultStatus = ResultStatus.Success,
                            Message = $"{updatedUser.UserName} basariyla guncellenmistir.",
                            User = updatedUser
                        },
                        UserUpdatePartial = await this.RenderViewToStringAsync("_UserUpdatePartial", userUpdateDto)
                    });
                    return Json(userUpdateAjax);
                }
                else
                {
                    //identity tarafinda olusacak hatalar icin
                    foreach (var err in result.Errors)
                    {
                        ModelState.AddModelError("", err.Description);
                    }
                    var userUpdateErrAjax = JsonSerializer.Serialize(new UserUpdateAjaxViewModel
                    {
                        UserUpdateDto = userUpdateDto,
                        UserUpdatePartial = await this.RenderViewToStringAsync("_UserUpdatePartial", userUpdateDto)
                    });
                    return Json(userUpdateErrAjax);
                }
            }
            else
            {
                var userUpdateErrModel = JsonSerializer.Serialize(new UserUpdateAjaxViewModel
                {
                    UserUpdateDto = userUpdateDto,
                    UserUpdatePartial = await this.RenderViewToStringAsync("_UserUpdatePartial", userUpdateDto)
                });
                return Json(userUpdateErrModel);
            }
        }

        [Authorize]
        [HttpGet]
        public async Task<ViewResult> ChangeDetail()
        {
            var user = await UserManager.GetUserAsync(HttpContext.User);
            var updateDto = Mapper.Map<UserUpdateDto>(user);
            return View(updateDto);
        }


        [Authorize]
        [HttpPost]
        public async Task<ViewResult> ChangeDetail(UserUpdateDto userUpdateDto)
        {

Mvc/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using Mvc.Models;
using Services.Abstract;
using Shared.Utilities.Results.ComplexTypes;

namespace Mvc.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;

        public ArticleController(IArticleService articleService)
        {
            _articleService = articleService;
        }

        [HttpGet]
        public async Task<IActionResult> Search(string keyword, int currentPage = 1, int pageSize = 5, bool isAscending = false)
        {
            var searchResult = await _articleService.SearchAsync(keyword, currentPage, pageSize, isAscending);
            if(searchResult.ResultStatus == ResultStatus.Success)
            {
                return View (new ArticleSearchViewModel
                {
                    ArticleListDto = searchResult.Data,
                    //keyword'ün tutulma sebebi, arama sonucunda dönen makaleler için de sayfalama yapılmasıdır
                    Keyword = keyword
                });
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int articleId)
        {
            var articleResult = await _articleService.GetAsync(articleId);
            if(articleResult.ResultStatus == ResultStatus.Success)
            {
                var userArticles = await _articleService.GetAllByUserIdOnFilter(articleResult.Data.Article.UserId,
                    Entities.ComplexTypes.FilterBy.Category, Entities.ComplexTypes.OrderBy.Date, false, 10, articleResult.Data.Article.CategoryId,
                    DateTime.Now, DateTime.Now, 0, 100000, 0, 100000);
                await _articleService.IncreaseViewCountAsync(articleId);
                return View(new ArticleDetailViewModel
                {
                    ArticleDto = articleResult.Data,
                    ArticleDetailRightSideBarViewModel = new ArticleDetailRightSideBarViewModel
                    {
                        ArticleListDto = userArticles.Data,
                        Header = "Kullanıcının Aynı Kategori Üzerindeki En Çok Okunan Makaleleri",
                        User = articleResult.Data.Article.User
                    }
                });
            }
            return NotFound();
        }
    }
}

Mvc/Controllers/CommentController.cs
using Entities.Dtos;
using Microsoft.AspNetCore.Mvc;
using Mvc.Models;
using Services.Abstract;
using Shared.Utilities.Extensions;
using Shared.Utilities.Results.ComplexTypes;
using Shared.Utilities.Results.Concrete;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Mvc.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }

        [HttpPost]
        public async Task<JsonResult> Add(CommentAddDto commentAddDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _commentService.AddAsync(commentAddDto);
                if(result.ResultStatus == ResultStatus.Success)
                {
                    var commentAddAjaxViewModel = JsonSerializer.Serialize(new CommentAddAjaxViewModel
                    {
                        CommentDto = result.Data,
                        CommentAddPartial = await this.RenderViewToStringAsync("_CommentAddPartial", commentAddDto)
                    }, new JsonSerializerOptions
                    {
                        ReferenceHandler = ReferenceHandler.Preserve
                    });
                    return Json(commentAddAjaxViewModel);
                }
                ModelState.AddModelError("", result.Message);
            }
            var commentAddAjaxErrorModel = JsonSerializer.Serialize(new CommentAddAjaxViewModel
            {
                CommentAddDto = commentAddDto,
                CommentAddPartial = await this.RenderViewToStringAsync("_CommentAddPartial", commentAddDto)
            });
            return Json(commentAddAjaxErrorModel);
        }
    }
}

Mvc/Areas/Admin/Views/Home/Index.cshtml
@model Mvc.Areas.Admin.Models.DashboardViewModel
@{
    Layout = "_Layout";
    ViewBag.Title = "Yonetim Paneli";
}
@*<h1 class="mt-4">Dashboard</h1>*@
<ol class="breadcrumb mb-3 mt-2">
    <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Admin</a></li>
    <li class="breadcrumb-item active"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Yonetim Panaeli</a></li>
</ol>
<div class="row">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="card-body">Makaleler (@Model.ArticlesCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Article" asp-action="Index">Detaylar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="card-body">Kategoriler (@Model.CategoriesCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Category" asp-action="Index">Detaylar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="card-body">Kullanicilar (@Model.UsersCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="User" asp-action="Index">Detaylar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="card-body">Yorumlar (@Model.CommentsCount)</div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Comment" asp-action="Index">Detaylar</a>
                <div class="small text-white"><i class="fas fa-angle-right"></i></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-6">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-area mr-1"></i>
                Area Chart Example
            </div>
            <div class="card-body"><canvas id="area-chart" width="100%" height="40"></canvas></div>
        </div>
    </div>
    <div class="col-xl-6">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-bar mr-1"></i>
                Bar Chart Example
            </div>
            <div class="card-body"><canvas id="bar-chart" width="100%" height="40"></canvas></div>
        </div>
    </div>
</div>
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Son Paylasilan Makaleler
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="articlesTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Baslik</th>
                        <th>Kategori</th>
                        <th>Resim</th>
                        <th>Paylasim Tarihi</th>
                        <th>Okunma Sayisi</th>
                        <th>Yorum Sayisi</th>
                        <th>Begeni Sayisi</th>
                        <th>Aktiflik</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Id</th>
                        <th>Baslik</th>
                        <th>Kategori</th>
                        <th>Resim</th>
                        <th>Paylasim Tarihi</th>
                        <th>Okunma Sayisi</th>
                        <th>Yorum Sayisi</th>
                        <th>Begeni Sayisi</th>
                        <th>Aktiflik</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var article in Model.Articles.Articles)
                    {
                        <tr>
                            <td>@article.ID</td>
                            <td>@article.Title</td>
                            <td>@article.Category.Name</td>
                            <td><img src="~/img/@article.ArticleThumbnail" class="my-image-table" /></td>
                            <td>@article.CreatedDate.ToShortDateString()</td>
                            <td>@article.ArticleView</td>
                            <td>@article.ArticleComment</td>
                            <td>@article.ArticleLike</td>
                            <td>@(article.IsActive ? "Evet" : "Hayir")</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts{
    <script src="~/Admin/js/homeindex.js" type="application/ecmascript"></script>

}