Mvc/Areas/Admin/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Entities.Concrete;
using Microsoft.EntityFrameworkCore;
using Entities.Dtos;
using System.Text.Json;
using AutoMapper;
using Mvc.Helpers.Abstract;
using Mvc.Areas.Admin.Models;
using Shared.Utilities.Results.ComplexTypes;
using Shared.Utilities.Extensions;

namespace Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RoleController : BaseController
    {
        private readonly RoleManager<Role> _roleManager;

        public RoleController(RoleManager<Role> roleManager, UserManager<User> userManager, IMapper mapper, IImageHelper imageHelper) : base(userManager, mapper, imageHelper)
        {
            _roleManager = roleManager;
        }

        [HttpGet]
        [Authorize(Roles = "SuperAdmin,Role.Read")]
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(new RoleListDto
            {
                Roles = roles
            });
        }

        [HttpGet]
        [Authorize(Roles = "SuperAdmin,Role.Read")]
        public async Task<IActionResult> GetAllRoles()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            var roleListDto = JsonSerializer.Serialize(new RoleListDto
            {
                Roles = roles
            });
            return Json(roleListDto);
        }

        [Authorize(Roles = "SuperAdmin,User.Update")]
        [HttpGet]
        public async Task<IActionResult> Assign(int userId)
        {
            //var user = await UserManager.FindByIdAsync(userId.ToString());
            var user = await UserManager.Users.SingleOrDefaultAsync(u => u.Id == userId);
            var roles = await _roleManager.Roles.ToListAsync();
            var userRoles = await UserManager.GetRolesAsync(user);
            UserRoleAssignDto userRoleAssignDto = new UserRoleAssignDto
            {
                UserId = user.Id,
                UserName = user.UserName
            };
            foreach (var role in roles)
            {
                RoleAssignDto rolesAssignDto = new RoleAssignDto
                {
                    RoleId = role.Id,
                    RoleName = role.Name,
                    HasRole = userRoles.Contains(role.Name)
                };
                userRoleAssignDto.RoleAssignDtos.Add(rolesAssignDto);
            }

            return PartialView("_RoleAssignPartial", userRoleAssignDto);
        }

        [Authorize(Roles = "SuperAdmin,User.Update")]
        [HttpPost]
        public async Task<IActionResult> Assign(UserRoleAssignDto userRoleAssignDto)
        {
            if (ModelState.IsValid)
            { 
                var user = await UserManager.Users.SingleOrDefaultAsync(u => u.Id == userRoleAssignDto.UserId);
                foreach (var roleAssignDto in userRoleAssignDto.RoleAssignDtos)
                {
                    if (roleAssignDto.HasRole)
                        await UserManager.AddToRoleAsync(user, roleAssignDto.RoleName);
                    else
                    {
                        await UserManager.RemoveFromRoleAsync(user, roleAssignDto.RoleName);
                    }
                }
                //rol atama işlemi gerçekleştikten sonra değişikliklerin gerçekleşmesi için rol atanan kullanıcının
                //çıkış yapmasına gerek kalmadan belirli bir süre sonra işlemin otoamatik gerçekleşmesi için bu işem yapılır
                await UserManager.UpdateSecurityStampAsync(user);

                var userRoleAssignAjaxViewModel = JsonSerializer.Serialize(new UserRoleAssignAjaxViewModel
                {
                    UserDto = new UserDto
                    {
                        User = user,
                        Message = $"{user.UserName} kullanıcısına ait rol atama işlemi başarıyla tamamlanmıştır.",
                        resultStatus = ResultStatus.Success
                    },
                    RoleAssignPartial = await this.RenderViewToStringAsync("_RoleAssignPartial", userRoleAssignDto)
                });
                return Json(userRoleAssignAjaxViewModel);
            }
            else
            {
                var userRoleAssignAjaxErrorModel = JsonSerializer.Serialize(new UserRoleAssignAjaxViewModel
                {
                    RoleAssignPartial = await this.RenderViewToStringAsync("_RoleAssignPartial", userRoleAssignDto),
                    UserRoleAssignDto = userRoleAssignDto
                });
                return Json(userRoleAssignAjaxErrorModel);
            }
        }
    }
}

Mvc/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using Mvc.Models;
using Services.Abstract;
using Shared.Utilities.Results.ComplexTypes;

namespace Mvc.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IArticleService _articleService;

        public ArticleController(IArticleService articleService)
        {
            _articleService = articleService;
        }

        [HttpGet]
        public async Task<IActionResult> Search(string keyword, int currentPage = 1, int pageSize = 5, bool isAscending = false)
        {
            var searchResult = await _articleService.SearchAsync(keyword, currentPage, pageSize, isAscending);
            if(searchResult.ResultStatus == ResultStatus.Success)
            {
                return View (new ArticleSearchViewModel
                {
                    ArticleListDto = searchResult.Data,
                    //keyword'ün tutulma sebebi, arama sonucunda dönen makaleler için de sayfalama yapılmasıdır
                    Keyword = keyword
                });
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int articleId)
        {
            var articleResult = await _articleService.GetAsync(articleId);
            if(articleResult.ResultStatus == ResultStatus.Success)
            {
                var userArticles = await _articleService.GetAllByUserIdOnFilter(articleResult.Data.Article.UserId,
                    Entities.ComplexTypes.FilterBy.Category, Entities.ComplexTypes.OrderBy.Date, false, 10, articleResult.Data.Article.CategoryId,
                    DateTime.Now, DateTime.Now, 0, 100000, 0, 100000);
                await _articleService.IncreaseViewCountAsync(articleId);
                return View(new ArticleDetailViewModel
                {
                    ArticleDto = articleResult.Data,
                    ArticleDetailRightSideBarViewModel = new ArticleDetailRightSideBarViewModel
                    {
                        ArticleListDto = userArticles.Data,
                        Header = "Kullanıcının Aynı Kategori Üzerindeki En Çok Okunan Makaleleri",
                        User = articleResult.Data.Article.User
                    }
                });
            }
            return NotFound();
        }
    }
}

Mvc/Controllers/CommentController.cs
using Entities.Dtos;
using Microsoft.AspNetCore.Mvc;
using Mvc.Models;
using Services.Abstract;
using Shared.Utilities.Extensions;
using Shared.Utilities.Results.ComplexTypes;
using Shared.Utilities.Results.Concrete;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Mvc.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }

        [HttpPost]
        public async Task<JsonResult> Add(CommentAddDto commentAddDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _commentService.AddAsync(commentAddDto);
                if(result.ResultStatus == ResultStatus.Success)
                {
                    var commentAddAjaxViewModel = JsonSerializer.Serialize(new CommentAddAjaxViewModel
                    {
                        CommentDto = result.Data,
                        CommentAddPartial = await this.RenderViewToStringAsync("_CommentAddPartial", commentAddDto)
                    }, new JsonSerializerOptions
                    {
                        ReferenceHandler = ReferenceHandler.Preserve
                    });
                    return Json(commentAddAjaxViewModel);
                }
                ModelState.AddModelError("", result.Message);
            }
            var commentAddAjaxErrorModel = JsonSerializer.Serialize(new CommentAddAjaxViewModel
            {
                CommentAddDto = commentAddDto,
                CommentAddPartial = await this.RenderViewToStringAsync("_CommentAddPartial", commentAddDto)
            });
            return Json(commentAddAjaxErrorModel);
        }
    }
}

Mvc/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Design - Blog</title>
    @await Html.PartialAsync("_layoutCssPartial")
    @await RenderSectionAsync("Styles",false);
    <link href="~/Admin/css/site.css" rel="stylesheet" />
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Paneli</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Arama..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        @await Component.InvokeAsync("TopBar")
    </nav>
    <div id="layoutSidenav">
        @await Component.InvokeAsync("AdminMenu")
        @*AdminMenu componentini calistirir*@
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @if (TempData["SuccessMessage"] !=null)
                    {
                    <div class="alert alert-success mt-2" role="alert">
                        @TempData["SuccessMessage"]
                    </div>
                    }
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Tüm Hakları Saklıdır &copy; Blog 2020</div>
                        <div>
                            <a href="#">Gizlilik Politikası</a>
                            &middot;
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    @await Html.PartialAsync("_layoutJsPartial")
@await RenderSectionAsync("Scripts",false);
</body>
</html>

Mvc/Areas/Admin/Views/Shared/_layoutCssPartial.cshtml
<link href="~/Admin/css/styles.css" rel="stylesheet" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css">
<link href="https://cdn.datatables.net/buttons/2.0.1/css/buttons.bootstrap5.min.css" rel="stylesheet" crossorigin="anonymous" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />

Mvc/Areas/Admin/Views/Shared/_layoutJsPartial.cshtml
<script src="https://code.jquery.com/jquery-3.6.1.js"
        integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/Admin/js/scripts.js"></script>
<script src="~/Admin/js/site.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.1.1/chart.min.js" integrity="sha512-MC1YbhseV2uYKljGJb7icPOjzF2k6mihfApPyPhEAo3NsLUW0bpgtL4xYWK1B+1OuSrUkfOTfhxrRKCz/Jp3rQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript" charset="utf8"
        src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>
<script src="~/Admin/assets/demo/datatables-demo.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/dataTables.buttons.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/5d6e25e9b6.js" crossorigin="anonymous"></script>
<script src="~/Admin/assets/demo/chart-area-demo.js"></script>
<script src="~/Admin/assets/demo/chart-bar-demo.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@@11"></script>
@await Component.InvokeAsync("NToastNotify")

Mvc/Areas/Admin/Views/Shared/_layoutSideNavPartial.cshtml
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">MENÜ</div>
                <a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading">İçerikler</div>
                <a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-th-list"></i></div>
                    Kategoriler
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Article" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-file-alt"></i></div>
                    Makaleler
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="Comment" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-comments"></i></div>
                    Yorumlar
                </a>
                <div class="sb-sidenav-menu-heading">Kullanıcılar</div>
                <a class="nav-link" asp-area="Admin" asp-controller="Role" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-user-shield"></i></div>
                    Roller
                </a>
                <a class="nav-link" asp-area="Admin" asp-controller="User" asp-action="Index">
                    <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
                    Kullanıcılar
                </a>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Giriş Yapan Kullanıcı:</div>
        </div>
    </nav>
</div>